//
// Ayah.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Ayah: Codable {

    public var number: Int
    public var audio: String?
    public var audioSecondary: [String]?
    public var surah: SurahSummary?
    public var text: String
    public var numberInSurah: Int
    public var juz: Int
    public var manzil: Int
    public var page: Int
    public var ruku: Int
    public var hizbQuarter: Int
    public var sajda: Bool?

    public init(number: Int, audio: String?, audioSecondary: [String]?, surah: SurahSummary?, text: String, numberInSurah: Int, juz: Int, manzil: Int, page: Int, ruku: Int, hizbQuarter: Int, sajda: Bool?) {
        self.number = number
        self.audio = audio
        self.audioSecondary = audioSecondary
        self.surah = surah
        self.text = text
        self.numberInSurah = numberInSurah
        self.juz = juz
        self.manzil = manzil
        self.page = page
        self.ruku = ruku
        self.hizbQuarter = hizbQuarter
        self.sajda = sajda
    }


}

