//
// EditionResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EditionResponse: Codable {

    public var code: Int?
    public var status: String?
    public var data: [Edition]?

    public init(code: Int?, status: String?, data: [Edition]?) {
        self.code = code
        self.status = status
        self.data = data
    }


}

