//
// Edition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Edition: Codable {

    public var identifier: String?
    public var language: String?
    public var name: String?
    public var englishName: String?
    public var format: String?
    public var type: String?

    public init(identifier: String?, language: String?, name: String?, englishName: String?, format: String?, type: String?) {
        self.identifier = identifier
        self.language = language
        self.name = name
        self.englishName = englishName
        self.format = format
        self.type = type
    }


}

