//
// EditionListResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EditionListResponse: Codable {

    public var status: String?
    public var code: Int?
    public var data: [String]?

    public init(status: String?, code: Int?, data: [String]?) {
        self.status = status
        self.code = code
        self.data = data
    }


}

