//
// Page.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Page: Codable {

    public var number: Int?
    public var ayahs: [Ayah]?
    public var edition: Edition?

    public init(number: Int?, ayahs: [Ayah]?, edition: Edition?) {
        self.number = number
        self.ayahs = ayahs
        self.edition = edition
    }


}

