//
// PageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PageResponse: Codable {

    public var code: Int?
    public var status: String?
    public var data: Page?

    public init(code: Int?, status: String?, data: Page?) {
        self.code = code
        self.status = status
        self.data = data
    }


}

