//
// SurahResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SurahResponse: Codable {

    public var code: Int?
    public var status: String?
    public var data: Surah?

    public init(code: Int?, status: String?, data: Surah?) {
        self.code = code
        self.status = status
        self.data = data
    }


}

