//
// SurahListResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SurahListResponse: Codable {

    public var code: Int?
    public var status: String?
    public var data: [SurahSummary]?

    public init(code: Int?, status: String?, data: [SurahSummary]?) {
        self.code = code
        self.status = status
        self.data = data
    }


}

