//
// Surah.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Surah: Codable {

    public var number: Int?
    public var name: String?
    public var englishName: String?
    public var englishNameTranslation: String?
    public var revelationType: String?
    public var numberOfAyahs: Int?
    public var ayahs: [Ayah]?
    public var edition: Edition?

    public init(number: Int?, name: String?, englishName: String?, englishNameTranslation: String?, revelationType: String?, numberOfAyahs: Int?, ayahs: [Ayah]?, edition: Edition?) {
        self.number = number
        self.name = name
        self.englishName = englishName
        self.englishNameTranslation = englishNameTranslation
        self.revelationType = revelationType
        self.numberOfAyahs = numberOfAyahs
        self.ayahs = ayahs
        self.edition = edition
    }


}

